# Generated by Django 2.2.9 on 2022-02-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('mob', models.CharField(blank=True, max_length=100, null=True)),
                ('tran_id', models.CharField(blank=True, max_length=100, null=True)),
                ('mode', models.CharField(blank=True, max_length=100, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('mem_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
