# Generated by Django 2.2.4 on 2020-01-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
    ]
