# Generated by Django 2.2.9 on 2022-03-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
