# Generated by Django 2.2.9 on 2020-03-08 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20200307_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('description', models.CharField(blank=True, max_length=80, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
