# Generated by Django 2.2.9 on 2020-04-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
