# Generated by Django 2.2.9 on 2020-04-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20200413_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
