# Generated by Django 2.2.9 on 2020-03-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='link',
        ),
        migrations.AddField(
            model_name='news',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='news/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='desc',
            field=models.CharField(max_length=250),
        ),
    ]
