# Generated by Django 2.2.9 on 2022-03-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='linkedin_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
