# Generated by Django 2.2.9 on 2022-03-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='batch',
            field=models.CharField(choices=[('2016-20', '2016-20'), ('2017-21', '2017-21'), ('2018-22', '2018-22'), ('2019-23', '2019-23'), ('2020-24', '2020-24'), ('2021-25', '2021-25')], default='2016-20', max_length=30),
        ),
        migrations.AlterField(
            model_name='team',
            name='batch',
            field=models.CharField(choices=[('Faculty', 'Faculty'), ('Web', 'Web')], default='Faculty', max_length=30),
        ),
    ]
