# Generated by Django 2.2.9 on 2022-03-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alumni_linkedin_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='linkedin_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
