# Generated by Django 2.2.9 on 2020-03-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200306_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='decription',
        ),
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
