# Generated by Django 2.2.9 on 2020-03-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_volunteer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mob', models.CharField(max_length=100)),
                ('alum', models.BooleanField(default=False)),
                ('batch', models.CharField(blank=True, max_length=100, null=True)),
                ('loc', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=100)),
                ('about', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
