# Generated by Django 2.2.9 on 2020-04-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_team_core'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='notices/')),
                ('type', models.BooleanField(default=True)),
            ],
        ),
    ]
