# Generated by Django 2.2.9 on 2022-02-02 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_evening'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='core',
        ),
    ]
