# Generated by Django 2.2.9 on 2022-02-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_team_core'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='batch',
            field=models.CharField(choices=[('Final', 'Final'), ('Third', 'Third')], default='Final', max_length=30),
        ),
    ]
