# Generated by Django 2.2.9 on 2022-02-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_team_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('description', models.TextField(blank=True, null=True)),
                ('batch', models.CharField(choices=[('First', '2016-20'), ('Second', '2017-21')], default='2016-20', max_length=30)),
            ],
        ),
    ]
