# Generated by Django 2.2.4 on 2020-01-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='eimage',
            field=models.ImageField(default=1, upload_to='check/'),
            preserve_default=False,
        ),
    ]
