# Generated by Django 2.2.4 on 2020-01-30 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_employee_eimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='eimage',
        ),
    ]
