# Generated by Django 2.2.4 on 2020-01-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0004_remove_employee_eimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('files', models.FileField(upload_to='notices/')),
                ('created_date', models.DateTimeField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'notices',
            },
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Notice',
        ),
        migrations.DeleteModel(
            name='Timetable',
        ),
    ]
