# Generated by Django 2.2.4 on 2020-01-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0005_auto_20200130_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notices',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notices',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notices',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='notices/'),
        ),
    ]
