# Generated by Django 2.2.4 on 2020-01-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0006_auto_20200131_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notices',
            name='eid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='notices',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
