# Generated by Django 2.2.4 on 2020-01-30 18:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0007_auto_20200131_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notices',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
